### ISSUE TITLE
automate the generation of hi-res maps for print

### ISSUE THREAD

**Issue by hancush** [datamade/erikson-edi#120]
phase one: research options for generating high-resolution maps for print from existing web maps. propose the best option, or justify a different approach.

**Comment by hancush** [comment]
more information here: https://github.com/datamade/DEALS/issues/16

**Comment by hancush** [comment]
some answers to guiding questions:

1. at what size are maps printed? **11x17**
2. how flexible is the design? **reasonably, in some cases necessarily, e.g., a data table for a county for 47 tracts won't fit inside the map area.**

**Comment by hancush** [comment]
- the report is printed on 8 1/2 x 11
- they also print the maps out separately on 11 x 17

**Comment by hancush** [comment]
i spent about half an hour on a couple of spikes for this, to get a better handle on where we stand. i tried:

- [`django-hardcopy`](https://github.com/loftylabs/django-hardcopy) - long story short, this did not deliver.
- running [headless chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) directly.
    - `--print-to-pdf`: weird formatting issues.
    - `--screenshot` with a large window size: promising! [here's the output](https://drive.google.com/file/d/1Epv1zX46ZfL_nz8GRqDUzlc-t2KM_EhJ/view?usp=sharing) of the unaltered map view, and here's the command i used: 

        ```
        chrome --headless --disable-gpu --screenshot --window-size=3300,5100 http://localhost:8000/map/?area=greater-east-st-louis
        ```

        there was a slight issue where the google maps tiles did not all load, but i think that might have to do with spoofing the window size, and we may be able to fix it with [a solution like this](https://groups.google.com/forum/#!topic/google-maps-js-api-v3/arWFGUapU3o).

**Comment by derekeder** [comment]
We are no longer planning on supporting this functionality.
