### ISSUE TITLE
import and display raw number of students surveyed meeting vulnerability thresholds

### ISSUE THREAD

**Issue by hancush** [datamade/erikson-edi#121]
the map displays the number of students surveyed, and the percent meeting vulnerability thresholds, but not the number of students meeting vulnerability thresholds. import that value and display it beneath the number of students surveyed.

<img width="586" alt="screen shot 2019-02-12 at 4 35 30 pm" src="https://user-images.githubusercontent.com/12176173/52672724-436aba80-2ee4-11e9-8213-dd63039ba687.png">

**Comment by jeancochrane** [comment]
#123 should close this. We're going to check with Erikson first to make sure that solution fits their needs.

**Comment by derekeder** [comment]
This is done.
